### ISSUE TITLE
Error in docker build instructions

### ISSUE THREAD

**Issue by deddc23efb** [easydns/certbot-dns-easydns#3]
The description for building a certbot docker includes the following example:
FROM certbot/certbotb
RUN pip install certbot-dns-easydns

That is incorrect - there is a typo in the first line.  It should read:
FROM certbot/certbot
RUN pip install certbot-dns-easydns

Thanks

**Comment by caleb-s-cullen** [comment]
Thanks very much for bringing this to our attention.  I have pushed an update (83f72a6a6d5e2f0f58a41c23550dd4856ff4d738 / v0.1.3) to correct the typo.
